config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  
  devise_for :users
  resources :users, only: [:update, :show, :index]
  
  resources :lists do
    resources :items, only: [:create, :index]
  end

  root "welcome#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :items
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
   rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    authorize @items
  end

  def new
    @item = Item.new
    authorize @item
  end

  def show
    @item = Item.find(params[:id])
     authorize @item
  end

  def edit
    @item = Item.find(params[:id])
     authorize @item
  end
 
   def create
     @item = Item.new(params.require(:item).permit(:name, :description, :public))
     authorize @item
     if @item.save
       redirect_to @item, notice: "Item was saved successfully."
     else
       flash.now[:error] = "Error creating item. Please try again."
       render :new
     end
   end
 
   def update
     @item = Item.find(params[:id])
     authorize @item
     if @item.update_attributes(params.require(:item).permit(:name, :description, :public))
       redirect_to @item
     else
       flash.now[:error] = "Error saving item. Please try again."
       render :edit
     end
   end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
     @lists = List.all
     authorize @lists
  end

  def new
     @list = List.new
     authorize @list
  end

  def show
     @list = List.find(params[:id])
     @items = @list.items
     authorize @list
  end

  def edit
     @list = List.find(params[:id])
     authorize @list
  end
 
   def create
     @list = List.new(params.require(:list).permit(:name, :public))
     authorize @list
     if @list.save
       redirect_to @list, notice: "List was saved successfully."
     else
       flash.now[:error] = "Error creating list. Please try again."
       render :new
     end
   end
 
   def update
     @list = List.find(params[:id])
     authorize @list
     if @list.update_attributes(params.require(:list).permit(:name, :public))
       redirect_to @list
     else
       flash.now[:error] = "Error saving list. Please try again."
       render :edit
     end
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
   before_action :authenticate_user!
  
  def index
    @users = User.all
  end
  

  def show
    @user = User.find(params[:id])
    @items = @user.items.visible_to(current_user)

  end
  
   def update
     if current_user.update_attributes(user_params)
       flash.now[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash.now[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:name)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [item] do |i| %>
<% if item.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(item.errors.count, "error") %>.</h4>
      <ul>
        <% item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(item.errors[:title]) do %>
    <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: "Enter Item" %>
  <% end %>
  
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<h1>All Items</h1>
<% @items.each do |Item| %>
<p><%= link_to item.title, item %></p>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to item.title, item %>
       </h4>
     </div>
   </div>
<% end %>

app/views/items/index.html.erb
<h1>All Items</h1>
<% @items.each do |item| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to item.title, item %>
       </h4>
     </div>
   </div>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>
<div class="row">
   <div class="col-md-8">
     <%= form_for @item do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter Item" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>

<div class="row">
  <div class="col-md-4">
    <% if policy(@item).edit? %>
    <%= link_to "Edit", edit_list_item_path(@list, @item), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloccitoff </title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
     <div class="container">
       <ul class="nav nav-tabs">
        <li><%= link_to "Bloccitoff", welcome_index_path %></li>
          <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
      </ul>

       <% if flash.now[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% end %>
       
      <%= yield %>
         
     </div>

  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for lists:</p>
     <ul>
       <li>Make sure the list is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @list do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter list name" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public list
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/lists/index.html.erb
<h1>Lists</h1>

<div class="row">
  <div class="col-md-8">
    <% @lists.each do |list| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to list.name, list %>
          </h4>
          <small>
            <%= list.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if policy(List.new).create? %>
      <%= link_to "New List", new_list_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for lists:</p>
     <ul>
       <li>Make sure the list is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @list do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter list name" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public list
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
 
 <% if policy(@list).update? %>
   <%= link_to "Edit List", edit_list_path, class: 'btn btn-success' %>
 <% end %>
 
 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @list.description %></p>
     <% @items.each do |item| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to item.title, [@list, item] %>
           </h4>
              <small>
                submitted <%= time_ago_in_words(item.created_at) %> ago by <%= item.user.name %><br>
              </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <% if policy(Item.new).create? %>
       <%= link_to "New Item", new_list_item_path(@list), class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccitoff </h1>
  <p>Bloccitoff is a resource for sharing links with your friends!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Bloccit will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Bloccit will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
  </div>
</div>